# Generated by Django 2.2.1 on 2019-07-02 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
